### ISSUE TITLE
Heartbot is case sensitive

### ISSUE THREAD

**Issue by Carlgo11** [digitalocean/heartbot#1]
Heartbot is case sensitive resulting in events not being triggered. Maybe all messages could be made into lowercase before checked with the regex?

**Comment by kamaln7** [comment]
Good point! This was fixed in a9ed833dbd4d2101cea3f2848142a29ffb49ecd8 so you can just run `npm update` and you should be good to go.

**Comment by Carlgo11** [comment]
Okay thank you! :smiley:
